clear; clc; clf();
t = linspace(0, 4*%pi, 1001);
n = 0:64;
xa = 3*cos(5*t + %pi/6);
xb = 3*cos(5*n + %pi/6);
xc = 2*exp(%i*(n/6 - %pi));
xd = cos(n/8).*cos(%pi*n/8);
xe = cos(%pi*n/2) - sin(%pi*n/8) + 3*cos(%pi*n/4 + %pi/3);
T0 = 2*%pi/5;
err_a = max(abs(3*cos(5*(t+T0)+%pi/6) - xa));
err_e = max(abs(xe(1:49) - xe(17:65)));
disp("Errors for continuous period 2*pi/5 and discrete period 16:");
disp([err_a err_e]);
subplot(3,2,1); plot(t,xa); title("(a) Periodic, T = 2*pi/5"); xlabel("t"); ylabel("xa(t)");
subplot(3,2,2); plot2d3(n,xb); title("(b) Nonperiodic"); xlabel("n"); ylabel("xb(n)");
subplot(3,2,3); plot2d3(n,real(xc)); title("(c) Real part"); xlabel("n"); ylabel("Re xc(n)");
subplot(3,2,4); plot2d3(n,imag(xc)); title("(c) Imaginary part"); xlabel("n"); ylabel("Im xc(n)");
subplot(3,2,5); plot2d3(n,xd); title("(d) Nonperiodic"); xlabel("n"); ylabel("xd(n)");
subplot(3,2,6); plot2d3(n,xe); title("(e) Periodic, N = 16"); xlabel("n"); ylabel("xe(n)");
